### ISSUE TITLE
Will not compile with recent toolchains

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/cromwell#1]
I've tried compiling this with the latest gcc / clang but the code is a nightmare.
Even with old standards it did not compile.

The `-Werror` and modern sophisticated error-checking don't help some of the 20+ year old code :)

**Comment by binarymaster** [comment]
This could be fixed with @thrimbor's [`build_fix`](https://github.com/thrimbor/cromwell/commits/build_fix) branch. Tested on GCC 4.4.3.

**Comment by mborgerson** [comment]
Closed by #4
