### ISSUE TITLE
Add ReactOS boot support

### ISSUE THREAD

**Issue by mborgerson** [XboxDev/cromwell#17]
Since the ReactOS port to Xbox has been recently revived, it's likely that users may want to boot ReactOS in addition to Linux.

@binarymaster has added this support recently [here](https://github.com/binarymaster/cromwell/tree/master), and those patches should be ported over to this repository.

**Comment by JayFoxRox** [comment]
Something that should be changed while working on this: 

- "Linux" XBE display title: https://github.com/XboxDev/cromwell/blob/179785ba79a7a533301ee9ab72ba35d0c98690df/boot_xbe/xbe.S#L50
- Linux logo: https://github.com/XboxDev/cromwell/blob/179785ba79a7a533301ee9ab72ba35d0c98690df/boot_xbe/xbe.S#L107
