### ISSUE TITLE
Xromwell causes Xbox to go into overheat mode with certain video resolutions enabled

### ISSUE THREAD

**Issue by GXTX** [XboxDev/cromwell#40]
There is a bug currently where if you have 480p or 1080i mode enable that Xromwell causes the Xbox to go into overheat mode then shutdown.

I have confirmed this with a device that presents as a HD AV Pack on my 1.0 Conexant.

**Comment by dreimer1986** [comment]
Confirmed same behavior on my PAL XBox v1.3 with Rocky5 Softmod 1.1.8

**Comment by haxar** [comment]
It was mentioned previously before by @GXTX that setting video mode to "Normal" & disabling 480p, 720p & 1080i works around this issue for Xromwell to boot.

**Comment by dreimer1986** [comment]
Sure it was, but correct me if I am wrong here.... this still makes it a bug and I reported that he is not alone with it.

**Comment by binarymaster** [comment]
@JayFoxRox I remember you had similar problem, please retest when possible, as this has been fixed.
