### ISSUE TITLE
GCC 10 build fails

### ISSUE THREAD

**Issue by CodeAsm** [XboxDev/cromwell#45]
OK ok, not completly.
xbe files works, and there is output for cromwell.bin and cromwell_1024.bin

But xqemu doesnt boot them, it just stays at black screen.
Thanks to the fellows on the Discord we found the gcc version 10 might be the isue here.
As suggested there, ive installed GCC 8, and modified the makefile to point to gcc-8 (Arch doesnt symlink to a gcc version, else ``CC=gcc-8 make`` might have worked? Thanks dracc for this idea)

I can build cromwell using gcc 8, but 10 is not so cute.
Using source cromwell-build-20200812-e2d1f85 or git clone.

`$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC) 
`
a different isue might be:
```BootFATX.c:6:1: note: 'strncmp' is defined in header '<string.h>'; did you forget to '#include <string.h>'?
    5 | #include "BootFATX.h"
  +++ |+#include <string.h>```
or does gcc10 just check more harder? a hex compare between 8 and 10 seems a small shift in code (resulting hash and jumps do reflect the compiler/linker being aware of whatever is happening). 
Does the slowly move towards x86_64 has anything to do with this? I hope I can help narrow down the isue or fix.

**Comment by CodeAsm** [comment]
To followup on the suggestion to disable optimisations:
removing  -O2 or changing it to 1, or 0 (compiler default) yields no apparent fix, xqemu does not run or atleast visibly.

Installed Gcc 9, wich compiles a fine working cromwell image. further investigation is nececairy, suggestions are welcome ofcourse.

**Comment by GXTX** [comment]
@CodeAsm So I tested this on GCC10, it seems to work perfectly fine on hardware.

**Comment by GXTX** [comment]
Went back and tested Xromwell and Cromwell, both are working fine. Not sure...

```
[wutno@6 cromwell]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC)
```

**Comment by GXTX** [comment]
Is this still an issue for you @CodeAsm?

**Comment by CodeAsm** [comment]
Doesnt seem to be the same error. Maybe i should open an new issue or investigate what im doing now. I meanwhile using gcc 11, the xbe gets build but no bios. My system might be unclean and consider this now my system to be at problem. ill contact you somewhere else if I can be confident my gcc toolchain is installed correctly. For other users reading this and this might be of intrest, im running arch linux and this should be the standard gcc toolset
