### ISSUE TITLE
Xromwell stuck 

### ISSUE THREAD

**Issue by thesender604** [XboxDev/cromwell#58]
Hi 
Just tried xromwell on my 128mb 1.0 xbox and it gets as far as initializing usb and just hangs i was interested in trying reactos after seeing a youtube video

**Comment by binarymaster** [comment]
Did you tried some older builds? In the releases section there are binaries uploaded for each commit, so you can test them.

**Comment by thesender604** [comment]
Hi

 Sorry for the late reply
Yes I did try an older version which didn't get stuck at the USB section
but unfortunately I couldn't get reactos to boot I will try some of the
other versions and let you know my findings. Keep up the great work

All the best

Brian

**Comment by binarymaster** [comment]
> Yes I did try an older version which didn't get stuck at the USB section

Would be nice to find exact version where it got broken.

**Comment by LillyWho** [comment]
Can confirm the same hang on a 1.4 revision with stock memory configuration. Latest build at the time of writing.

**Comment by thesender604** [comment]
Hi

Sorry not been in touch life just keeps getting in the way I hope to try
some if the back builds this week and let you know which versions are
broken.

All the best

Brian

**Comment by thesender604** [comment]
1. Hi Stanislav.
   2.
   3. Well i finally got round to testing all the builds and the only one
   that gets stuck on the init usb .
   4.
   5. is build-20220311-7164224

*all versions before that are fine *

*All the Best *

*Brian*
